[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5174
  framework = "#custom"

[context.branch-deploy]
  command = "npm run build"

[[redirects]]
  from = "/clerk/*"
  to = "https://frontend-api.clerk.dev/*"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
